import one from "./web/list_page/1.png";
import two from "./web/list_page/2.png";
import three from "./web/list_page/3.png";
import four from "./web/list_page/4.png";
import five from "./web/list_page/5.png";
import six from "./web/list_page/6.png";
import seven from "./web/list_page/7.png";
import eight from "./web/list_page/8.png";
import nine from "./web/list_page/9.png";
import Profile from "./web/list_page/profile.png";
import RectImage from "./web/detail_page/Rectangle_24.png";
import Banner from "./mobile/detail/img.png";

const assets: Object = {
  0: {
    img: one,
    location: "Chennai",
    date: "12/08/2021",
    title: "Feed Stray Dogs amid covid pandamic lockdown",
    profile: Profile,
    user: "by Chennai Stray Care",
    raised: 25000,
    goal: 50000,
    left: 6,
    value: 50,
    banner: RectImage,
    mbanner: Banner,
    supporters: 925,
    shares: 2162,
    raisedByShare: 19400,
    topSupporters: [
      {
        profile: Profile,
        name: "John Doe",
        amount: 4000,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 2700,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 2400,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 1800,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 1500,
      },
    ],
    content: {
      overview: [
        "overview Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam officia nihil provident porro maxime, quo quos, reprehenderit quisquam laboriosam natus, fugit deserunt ab incidunt. Corporis, nulla quo. Excepturi, perferendis porro?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, et! Dignissimos est alias labore eos tenetur incidunt magnam odio doloribus? Incidunt labore molestias ut natus ab odit soluta repellendus iusto.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quasi doloribus dignissimos! Aspernatur officia labore dolorem culpa, architecto facere alias illo eaque non modi adipisci quo, voluptas, esse saepe laudantium.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem officiis numquam quia eveniet assumenda, eligendi harum repudiandae quidem soluta eaque nihil culpa perferendis necessitatibus id quisquam provident iste cupiditate consequatur?",
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus laudantium aspernatur quaerat praesentium laboriosam nemo excepturi ad delectus? Adipisci fuga ipsum est. Officiis blanditiis ab velit unde, recusandae maiores quia?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci excepturi, sunt dolore, reprehenderit illo atque corporis dignissimos repudiandae quos commodi similique molestias quis, debitis nemo eius. Quasi aspernatur recusandae magni.",
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur harum quaerat expedita deserunt. Numquam at rerum, consequuntur cumque provident alias atque culpa! Numquam, enim. Expedita minima mollitia consequuntur totam perspiciatis?",
      ],
      updates: [
        "updates Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam officia nihil provident porro maxime, quo quos, reprehenderit quisquam laboriosam natus, fugit deserunt ab incidunt. Corporis, nulla quo. Excepturi, perferendis porro?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, et! Dignissimos est alias labore eos tenetur incidunt magnam odio doloribus? Incidunt labore molestias ut natus ab odit soluta repellendus iusto.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quasi doloribus dignissimos! Aspernatur officia labore dolorem culpa, architecto facere alias illo eaque non modi adipisci quo, voluptas, esse saepe laudantium.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem officiis numquam quia eveniet assumenda, eligendi harum repudiandae quidem soluta eaque nihil culpa perferendis necessitatibus id quisquam provident iste cupiditate consequatur?",
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus laudantium aspernatur quaerat praesentium laboriosam nemo excepturi ad delectus? Adipisci fuga ipsum est. Officiis blanditiis ab velit unde, recusandae maiores quia?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci excepturi, sunt dolore, reprehenderit illo atque corporis dignissimos repudiandae quos commodi similique molestias quis, debitis nemo eius. Quasi aspernatur recusandae magni.",
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur harum quaerat expedita deserunt. Numquam at rerum, consequuntur cumque provident alias atque culpa! Numquam, enim. Expedita minima mollitia consequuntur totam perspiciatis?",
      ],
      comments: [
        "comments Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam officia nihil provident porro maxime, quo quos, reprehenderit quisquam laboriosam natus, fugit deserunt ab incidunt. Corporis, nulla quo. Excepturi, perferendis porro?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, et! Dignissimos est alias labore eos tenetur incidunt magnam odio doloribus? Incidunt labore molestias ut natus ab odit soluta repellendus iusto.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quasi doloribus dignissimos! Aspernatur officia labore dolorem culpa, architecto facere alias illo eaque non modi adipisci quo, voluptas, esse saepe laudantium.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem officiis numquam quia eveniet assumenda, eligendi harum repudiandae quidem soluta eaque nihil culpa perferendis necessitatibus id quisquam provident iste cupiditate consequatur?",
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus laudantium aspernatur quaerat praesentium laboriosam nemo excepturi ad delectus? Adipisci fuga ipsum est. Officiis blanditiis ab velit unde, recusandae maiores quia?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci excepturi, sunt dolore, reprehenderit illo atque corporis dignissimos repudiandae quos commodi similique molestias quis, debitis nemo eius. Quasi aspernatur recusandae magni.",
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur harum quaerat expedita deserunt. Numquam at rerum, consequuntur cumque provident alias atque culpa! Numquam, enim. Expedita minima mollitia consequuntur totam perspiciatis?",
      ],
    },
  },
  1: {
    img: two,
    location: "Chennai",
    date: "12/08/2021",
    title: "Helping Stray Dogs for better food and Shelter",
    profile: Profile,
    user: "by Chennai Stray Care",
    raised: 25000,
    goal: 50000,
    left: 6,
    value: 50,
    banner: RectImage,
    mbanner: Banner,
    supporters: 925,
    shares: 2162,
    raisedByShare: 19400,
    topSupporters: [
      {
        profile: Profile,
        name: "John Doe",
        amount: 4000,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 2700,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 2400,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 1800,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 1500,
      },
    ],
    content: {
      overview: [
        "overview Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam officia nihil provident porro maxime, quo quos, reprehenderit quisquam laboriosam natus, fugit deserunt ab incidunt. Corporis, nulla quo. Excepturi, perferendis porro?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, et! Dignissimos est alias labore eos tenetur incidunt magnam odio doloribus? Incidunt labore molestias ut natus ab odit soluta repellendus iusto.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quasi doloribus dignissimos! Aspernatur officia labore dolorem culpa, architecto facere alias illo eaque non modi adipisci quo, voluptas, esse saepe laudantium.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem officiis numquam quia eveniet assumenda, eligendi harum repudiandae quidem soluta eaque nihil culpa perferendis necessitatibus id quisquam provident iste cupiditate consequatur?",
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus laudantium aspernatur quaerat praesentium laboriosam nemo excepturi ad delectus? Adipisci fuga ipsum est. Officiis blanditiis ab velit unde, recusandae maiores quia?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci excepturi, sunt dolore, reprehenderit illo atque corporis dignissimos repudiandae quos commodi similique molestias quis, debitis nemo eius. Quasi aspernatur recusandae magni.",
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur harum quaerat expedita deserunt. Numquam at rerum, consequuntur cumque provident alias atque culpa! Numquam, enim. Expedita minima mollitia consequuntur totam perspiciatis?",
      ],
      updates: [
        "updates Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam officia nihil provident porro maxime, quo quos, reprehenderit quisquam laboriosam natus, fugit deserunt ab incidunt. Corporis, nulla quo. Excepturi, perferendis porro?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, et! Dignissimos est alias labore eos tenetur incidunt magnam odio doloribus? Incidunt labore molestias ut natus ab odit soluta repellendus iusto.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quasi doloribus dignissimos! Aspernatur officia labore dolorem culpa, architecto facere alias illo eaque non modi adipisci quo, voluptas, esse saepe laudantium.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem officiis numquam quia eveniet assumenda, eligendi harum repudiandae quidem soluta eaque nihil culpa perferendis necessitatibus id quisquam provident iste cupiditate consequatur?",
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus laudantium aspernatur quaerat praesentium laboriosam nemo excepturi ad delectus? Adipisci fuga ipsum est. Officiis blanditiis ab velit unde, recusandae maiores quia?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci excepturi, sunt dolore, reprehenderit illo atque corporis dignissimos repudiandae quos commodi similique molestias quis, debitis nemo eius. Quasi aspernatur recusandae magni.",
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur harum quaerat expedita deserunt. Numquam at rerum, consequuntur cumque provident alias atque culpa! Numquam, enim. Expedita minima mollitia consequuntur totam perspiciatis?",
      ],
      comments: [
        "comments Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam officia nihil provident porro maxime, quo quos, reprehenderit quisquam laboriosam natus, fugit deserunt ab incidunt. Corporis, nulla quo. Excepturi, perferendis porro?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, et! Dignissimos est alias labore eos tenetur incidunt magnam odio doloribus? Incidunt labore molestias ut natus ab odit soluta repellendus iusto.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quasi doloribus dignissimos! Aspernatur officia labore dolorem culpa, architecto facere alias illo eaque non modi adipisci quo, voluptas, esse saepe laudantium.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem officiis numquam quia eveniet assumenda, eligendi harum repudiandae quidem soluta eaque nihil culpa perferendis necessitatibus id quisquam provident iste cupiditate consequatur?",
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus laudantium aspernatur quaerat praesentium laboriosam nemo excepturi ad delectus? Adipisci fuga ipsum est. Officiis blanditiis ab velit unde, recusandae maiores quia?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci excepturi, sunt dolore, reprehenderit illo atque corporis dignissimos repudiandae quos commodi similique molestias quis, debitis nemo eius. Quasi aspernatur recusandae magni.",
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur harum quaerat expedita deserunt. Numquam at rerum, consequuntur cumque provident alias atque culpa! Numquam, enim. Expedita minima mollitia consequuntur totam perspiciatis?",
      ],
    },
  },
  2: {
    img: three,
    location: "Chennai",
    date: "12/08/2021",
    title: "Help Stray Dogs and Cats during pandemic situation",
    profile: Profile,
    user: "by Chennai Stray Care",
    raised: 25000,
    goal: 50000,
    left: 6,
    value: 50,
    banner: RectImage,
    mbanner: Banner,
    supporters: 925,
    shares: 2162,
    raisedByShare: 19400,
    topSupporters: [
      {
        profile: Profile,
        name: "John Doe",
        amount: 4000,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 2700,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 2400,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 1800,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 1500,
      },
    ],
    content: {
      overview: [
        "overview Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam officia nihil provident porro maxime, quo quos, reprehenderit quisquam laboriosam natus, fugit deserunt ab incidunt. Corporis, nulla quo. Excepturi, perferendis porro?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, et! Dignissimos est alias labore eos tenetur incidunt magnam odio doloribus? Incidunt labore molestias ut natus ab odit soluta repellendus iusto.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quasi doloribus dignissimos! Aspernatur officia labore dolorem culpa, architecto facere alias illo eaque non modi adipisci quo, voluptas, esse saepe laudantium.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem officiis numquam quia eveniet assumenda, eligendi harum repudiandae quidem soluta eaque nihil culpa perferendis necessitatibus id quisquam provident iste cupiditate consequatur?",
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus laudantium aspernatur quaerat praesentium laboriosam nemo excepturi ad delectus? Adipisci fuga ipsum est. Officiis blanditiis ab velit unde, recusandae maiores quia?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci excepturi, sunt dolore, reprehenderit illo atque corporis dignissimos repudiandae quos commodi similique molestias quis, debitis nemo eius. Quasi aspernatur recusandae magni.",
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur harum quaerat expedita deserunt. Numquam at rerum, consequuntur cumque provident alias atque culpa! Numquam, enim. Expedita minima mollitia consequuntur totam perspiciatis?",
      ],
      updates: [
        "updates Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam officia nihil provident porro maxime, quo quos, reprehenderit quisquam laboriosam natus, fugit deserunt ab incidunt. Corporis, nulla quo. Excepturi, perferendis porro?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, et! Dignissimos est alias labore eos tenetur incidunt magnam odio doloribus? Incidunt labore molestias ut natus ab odit soluta repellendus iusto.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quasi doloribus dignissimos! Aspernatur officia labore dolorem culpa, architecto facere alias illo eaque non modi adipisci quo, voluptas, esse saepe laudantium.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem officiis numquam quia eveniet assumenda, eligendi harum repudiandae quidem soluta eaque nihil culpa perferendis necessitatibus id quisquam provident iste cupiditate consequatur?",
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus laudantium aspernatur quaerat praesentium laboriosam nemo excepturi ad delectus? Adipisci fuga ipsum est. Officiis blanditiis ab velit unde, recusandae maiores quia?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci excepturi, sunt dolore, reprehenderit illo atque corporis dignissimos repudiandae quos commodi similique molestias quis, debitis nemo eius. Quasi aspernatur recusandae magni.",
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur harum quaerat expedita deserunt. Numquam at rerum, consequuntur cumque provident alias atque culpa! Numquam, enim. Expedita minima mollitia consequuntur totam perspiciatis?",
      ],
      comments: [
        "comments Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam officia nihil provident porro maxime, quo quos, reprehenderit quisquam laboriosam natus, fugit deserunt ab incidunt. Corporis, nulla quo. Excepturi, perferendis porro?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, et! Dignissimos est alias labore eos tenetur incidunt magnam odio doloribus? Incidunt labore molestias ut natus ab odit soluta repellendus iusto.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quasi doloribus dignissimos! Aspernatur officia labore dolorem culpa, architecto facere alias illo eaque non modi adipisci quo, voluptas, esse saepe laudantium.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem officiis numquam quia eveniet assumenda, eligendi harum repudiandae quidem soluta eaque nihil culpa perferendis necessitatibus id quisquam provident iste cupiditate consequatur?",
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus laudantium aspernatur quaerat praesentium laboriosam nemo excepturi ad delectus? Adipisci fuga ipsum est. Officiis blanditiis ab velit unde, recusandae maiores quia?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci excepturi, sunt dolore, reprehenderit illo atque corporis dignissimos repudiandae quos commodi similique molestias quis, debitis nemo eius. Quasi aspernatur recusandae magni.",
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur harum quaerat expedita deserunt. Numquam at rerum, consequuntur cumque provident alias atque culpa! Numquam, enim. Expedita minima mollitia consequuntur totam perspiciatis?",
      ],
    },
  },
  3: {
    img: four,
    location: "Chennai",
    date: "12/08/2021",
    title: "Feed Stray Dogs amid covid pandamic lockdown",
    profile: Profile,
    user: "by Chennai Stray Care",
    raised: 25000,
    goal: 50000,
    left: 6,
    value: 50,
    banner: RectImage,
    mbanner: Banner,
    supporters: 925,
    shares: 2162,
    raisedByShare: 19400,
    topSupporters: [
      {
        profile: Profile,
        name: "John Doe",
        amount: 4000,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 2700,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 2400,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 1800,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 1500,
      },
    ],
    content: {
      overview: [
        "overview Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam officia nihil provident porro maxime, quo quos, reprehenderit quisquam laboriosam natus, fugit deserunt ab incidunt. Corporis, nulla quo. Excepturi, perferendis porro?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, et! Dignissimos est alias labore eos tenetur incidunt magnam odio doloribus? Incidunt labore molestias ut natus ab odit soluta repellendus iusto.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quasi doloribus dignissimos! Aspernatur officia labore dolorem culpa, architecto facere alias illo eaque non modi adipisci quo, voluptas, esse saepe laudantium.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem officiis numquam quia eveniet assumenda, eligendi harum repudiandae quidem soluta eaque nihil culpa perferendis necessitatibus id quisquam provident iste cupiditate consequatur?",
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus laudantium aspernatur quaerat praesentium laboriosam nemo excepturi ad delectus? Adipisci fuga ipsum est. Officiis blanditiis ab velit unde, recusandae maiores quia?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci excepturi, sunt dolore, reprehenderit illo atque corporis dignissimos repudiandae quos commodi similique molestias quis, debitis nemo eius. Quasi aspernatur recusandae magni.",
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur harum quaerat expedita deserunt. Numquam at rerum, consequuntur cumque provident alias atque culpa! Numquam, enim. Expedita minima mollitia consequuntur totam perspiciatis?",
      ],
      updates: [
        "updates Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam officia nihil provident porro maxime, quo quos, reprehenderit quisquam laboriosam natus, fugit deserunt ab incidunt. Corporis, nulla quo. Excepturi, perferendis porro?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, et! Dignissimos est alias labore eos tenetur incidunt magnam odio doloribus? Incidunt labore molestias ut natus ab odit soluta repellendus iusto.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quasi doloribus dignissimos! Aspernatur officia labore dolorem culpa, architecto facere alias illo eaque non modi adipisci quo, voluptas, esse saepe laudantium.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem officiis numquam quia eveniet assumenda, eligendi harum repudiandae quidem soluta eaque nihil culpa perferendis necessitatibus id quisquam provident iste cupiditate consequatur?",
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus laudantium aspernatur quaerat praesentium laboriosam nemo excepturi ad delectus? Adipisci fuga ipsum est. Officiis blanditiis ab velit unde, recusandae maiores quia?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci excepturi, sunt dolore, reprehenderit illo atque corporis dignissimos repudiandae quos commodi similique molestias quis, debitis nemo eius. Quasi aspernatur recusandae magni.",
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur harum quaerat expedita deserunt. Numquam at rerum, consequuntur cumque provident alias atque culpa! Numquam, enim. Expedita minima mollitia consequuntur totam perspiciatis?",
      ],
      comments: [
        "comments Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam officia nihil provident porro maxime, quo quos, reprehenderit quisquam laboriosam natus, fugit deserunt ab incidunt. Corporis, nulla quo. Excepturi, perferendis porro?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, et! Dignissimos est alias labore eos tenetur incidunt magnam odio doloribus? Incidunt labore molestias ut natus ab odit soluta repellendus iusto.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quasi doloribus dignissimos! Aspernatur officia labore dolorem culpa, architecto facere alias illo eaque non modi adipisci quo, voluptas, esse saepe laudantium.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem officiis numquam quia eveniet assumenda, eligendi harum repudiandae quidem soluta eaque nihil culpa perferendis necessitatibus id quisquam provident iste cupiditate consequatur?",
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus laudantium aspernatur quaerat praesentium laboriosam nemo excepturi ad delectus? Adipisci fuga ipsum est. Officiis blanditiis ab velit unde, recusandae maiores quia?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci excepturi, sunt dolore, reprehenderit illo atque corporis dignissimos repudiandae quos commodi similique molestias quis, debitis nemo eius. Quasi aspernatur recusandae magni.",
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur harum quaerat expedita deserunt. Numquam at rerum, consequuntur cumque provident alias atque culpa! Numquam, enim. Expedita minima mollitia consequuntur totam perspiciatis?",
      ],
    },
  },
  4: {
    img: five,
    location: "Chennai",
    date: "12/08/2021",
    title: "Helping Stray Dogs for better food and Shelter",
    profile: Profile,
    user: "by Chennai Stray Care",
    raised: 25000,
    goal: 50000,
    left: 6,
    value: 50,
    banner: RectImage,
    mbanner: Banner,
    supporters: 925,
    shares: 2162,
    raisedByShare: 19400,
    topSupporters: [
      {
        profile: Profile,
        name: "John Doe",
        amount: 4000,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 2700,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 2400,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 1800,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 1500,
      },
    ],
    content: {
      overview: [
        "overview Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam officia nihil provident porro maxime, quo quos, reprehenderit quisquam laboriosam natus, fugit deserunt ab incidunt. Corporis, nulla quo. Excepturi, perferendis porro?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, et! Dignissimos est alias labore eos tenetur incidunt magnam odio doloribus? Incidunt labore molestias ut natus ab odit soluta repellendus iusto.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quasi doloribus dignissimos! Aspernatur officia labore dolorem culpa, architecto facere alias illo eaque non modi adipisci quo, voluptas, esse saepe laudantium.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem officiis numquam quia eveniet assumenda, eligendi harum repudiandae quidem soluta eaque nihil culpa perferendis necessitatibus id quisquam provident iste cupiditate consequatur?",
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus laudantium aspernatur quaerat praesentium laboriosam nemo excepturi ad delectus? Adipisci fuga ipsum est. Officiis blanditiis ab velit unde, recusandae maiores quia?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci excepturi, sunt dolore, reprehenderit illo atque corporis dignissimos repudiandae quos commodi similique molestias quis, debitis nemo eius. Quasi aspernatur recusandae magni.",
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur harum quaerat expedita deserunt. Numquam at rerum, consequuntur cumque provident alias atque culpa! Numquam, enim. Expedita minima mollitia consequuntur totam perspiciatis?",
      ],
      updates: [
        "updates Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam officia nihil provident porro maxime, quo quos, reprehenderit quisquam laboriosam natus, fugit deserunt ab incidunt. Corporis, nulla quo. Excepturi, perferendis porro?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, et! Dignissimos est alias labore eos tenetur incidunt magnam odio doloribus? Incidunt labore molestias ut natus ab odit soluta repellendus iusto.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quasi doloribus dignissimos! Aspernatur officia labore dolorem culpa, architecto facere alias illo eaque non modi adipisci quo, voluptas, esse saepe laudantium.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem officiis numquam quia eveniet assumenda, eligendi harum repudiandae quidem soluta eaque nihil culpa perferendis necessitatibus id quisquam provident iste cupiditate consequatur?",
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus laudantium aspernatur quaerat praesentium laboriosam nemo excepturi ad delectus? Adipisci fuga ipsum est. Officiis blanditiis ab velit unde, recusandae maiores quia?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci excepturi, sunt dolore, reprehenderit illo atque corporis dignissimos repudiandae quos commodi similique molestias quis, debitis nemo eius. Quasi aspernatur recusandae magni.",
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur harum quaerat expedita deserunt. Numquam at rerum, consequuntur cumque provident alias atque culpa! Numquam, enim. Expedita minima mollitia consequuntur totam perspiciatis?",
      ],
      comments: [
        "comments Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam officia nihil provident porro maxime, quo quos, reprehenderit quisquam laboriosam natus, fugit deserunt ab incidunt. Corporis, nulla quo. Excepturi, perferendis porro?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, et! Dignissimos est alias labore eos tenetur incidunt magnam odio doloribus? Incidunt labore molestias ut natus ab odit soluta repellendus iusto.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quasi doloribus dignissimos! Aspernatur officia labore dolorem culpa, architecto facere alias illo eaque non modi adipisci quo, voluptas, esse saepe laudantium.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem officiis numquam quia eveniet assumenda, eligendi harum repudiandae quidem soluta eaque nihil culpa perferendis necessitatibus id quisquam provident iste cupiditate consequatur?",
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus laudantium aspernatur quaerat praesentium laboriosam nemo excepturi ad delectus? Adipisci fuga ipsum est. Officiis blanditiis ab velit unde, recusandae maiores quia?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci excepturi, sunt dolore, reprehenderit illo atque corporis dignissimos repudiandae quos commodi similique molestias quis, debitis nemo eius. Quasi aspernatur recusandae magni.",
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur harum quaerat expedita deserunt. Numquam at rerum, consequuntur cumque provident alias atque culpa! Numquam, enim. Expedita minima mollitia consequuntur totam perspiciatis?",
      ],
    },
  },
  5: {
    img: six,
    location: "Chennai",
    date: "12/08/2021",
    title: "Help Stray Dogs and Cats during pandemic situation",
    profile: Profile,
    user: "by Chennai Stray Care",
    raised: 25000,
    goal: 50000,
    left: 6,
    value: 50,
    banner: RectImage,
    mbanner: Banner,
    supporters: 925,
    shares: 2162,
    raisedByShare: 19400,
    topSupporters: [
      {
        profile: Profile,
        name: "John Doe",
        amount: 4000,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 2700,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 2400,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 1800,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 1500,
      },
    ],
    content: {
      overview: [
        "overview Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam officia nihil provident porro maxime, quo quos, reprehenderit quisquam laboriosam natus, fugit deserunt ab incidunt. Corporis, nulla quo. Excepturi, perferendis porro?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, et! Dignissimos est alias labore eos tenetur incidunt magnam odio doloribus? Incidunt labore molestias ut natus ab odit soluta repellendus iusto.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quasi doloribus dignissimos! Aspernatur officia labore dolorem culpa, architecto facere alias illo eaque non modi adipisci quo, voluptas, esse saepe laudantium.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem officiis numquam quia eveniet assumenda, eligendi harum repudiandae quidem soluta eaque nihil culpa perferendis necessitatibus id quisquam provident iste cupiditate consequatur?",
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus laudantium aspernatur quaerat praesentium laboriosam nemo excepturi ad delectus? Adipisci fuga ipsum est. Officiis blanditiis ab velit unde, recusandae maiores quia?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci excepturi, sunt dolore, reprehenderit illo atque corporis dignissimos repudiandae quos commodi similique molestias quis, debitis nemo eius. Quasi aspernatur recusandae magni.",
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur harum quaerat expedita deserunt. Numquam at rerum, consequuntur cumque provident alias atque culpa! Numquam, enim. Expedita minima mollitia consequuntur totam perspiciatis?",
      ],
      updates: [
        "updates Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam officia nihil provident porro maxime, quo quos, reprehenderit quisquam laboriosam natus, fugit deserunt ab incidunt. Corporis, nulla quo. Excepturi, perferendis porro?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, et! Dignissimos est alias labore eos tenetur incidunt magnam odio doloribus? Incidunt labore molestias ut natus ab odit soluta repellendus iusto.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quasi doloribus dignissimos! Aspernatur officia labore dolorem culpa, architecto facere alias illo eaque non modi adipisci quo, voluptas, esse saepe laudantium.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem officiis numquam quia eveniet assumenda, eligendi harum repudiandae quidem soluta eaque nihil culpa perferendis necessitatibus id quisquam provident iste cupiditate consequatur?",
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus laudantium aspernatur quaerat praesentium laboriosam nemo excepturi ad delectus? Adipisci fuga ipsum est. Officiis blanditiis ab velit unde, recusandae maiores quia?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci excepturi, sunt dolore, reprehenderit illo atque corporis dignissimos repudiandae quos commodi similique molestias quis, debitis nemo eius. Quasi aspernatur recusandae magni.",
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur harum quaerat expedita deserunt. Numquam at rerum, consequuntur cumque provident alias atque culpa! Numquam, enim. Expedita minima mollitia consequuntur totam perspiciatis?",
      ],
      comments: [
        "comments Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam officia nihil provident porro maxime, quo quos, reprehenderit quisquam laboriosam natus, fugit deserunt ab incidunt. Corporis, nulla quo. Excepturi, perferendis porro?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, et! Dignissimos est alias labore eos tenetur incidunt magnam odio doloribus? Incidunt labore molestias ut natus ab odit soluta repellendus iusto.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quasi doloribus dignissimos! Aspernatur officia labore dolorem culpa, architecto facere alias illo eaque non modi adipisci quo, voluptas, esse saepe laudantium.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem officiis numquam quia eveniet assumenda, eligendi harum repudiandae quidem soluta eaque nihil culpa perferendis necessitatibus id quisquam provident iste cupiditate consequatur?",
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus laudantium aspernatur quaerat praesentium laboriosam nemo excepturi ad delectus? Adipisci fuga ipsum est. Officiis blanditiis ab velit unde, recusandae maiores quia?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci excepturi, sunt dolore, reprehenderit illo atque corporis dignissimos repudiandae quos commodi similique molestias quis, debitis nemo eius. Quasi aspernatur recusandae magni.",
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur harum quaerat expedita deserunt. Numquam at rerum, consequuntur cumque provident alias atque culpa! Numquam, enim. Expedita minima mollitia consequuntur totam perspiciatis?",
      ],
    },
  },
  6: {
    img: seven,
    location: "Chennai",
    date: "12/08/2021",
    title: "Feed Stray Dogs amid covid pandamic lockdown",
    profile: Profile,
    user: "by Chennai Stray Care",
    raised: 25000,
    goal: 50000,
    left: 6,
    value: 50,
    banner: RectImage,
    mbanner: Banner,
    supporters: 925,
    shares: 2162,
    raisedByShare: 19400,
    topSupporters: [
      {
        profile: Profile,
        name: "John Doe",
        amount: 4000,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 2700,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 2400,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 1800,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 1500,
      },
    ],
    content: {
      overview: [
        "overview Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam officia nihil provident porro maxime, quo quos, reprehenderit quisquam laboriosam natus, fugit deserunt ab incidunt. Corporis, nulla quo. Excepturi, perferendis porro?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, et! Dignissimos est alias labore eos tenetur incidunt magnam odio doloribus? Incidunt labore molestias ut natus ab odit soluta repellendus iusto.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quasi doloribus dignissimos! Aspernatur officia labore dolorem culpa, architecto facere alias illo eaque non modi adipisci quo, voluptas, esse saepe laudantium.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem officiis numquam quia eveniet assumenda, eligendi harum repudiandae quidem soluta eaque nihil culpa perferendis necessitatibus id quisquam provident iste cupiditate consequatur?",
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus laudantium aspernatur quaerat praesentium laboriosam nemo excepturi ad delectus? Adipisci fuga ipsum est. Officiis blanditiis ab velit unde, recusandae maiores quia?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci excepturi, sunt dolore, reprehenderit illo atque corporis dignissimos repudiandae quos commodi similique molestias quis, debitis nemo eius. Quasi aspernatur recusandae magni.",
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur harum quaerat expedita deserunt. Numquam at rerum, consequuntur cumque provident alias atque culpa! Numquam, enim. Expedita minima mollitia consequuntur totam perspiciatis?",
      ],
      updates: [
        "updates Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam officia nihil provident porro maxime, quo quos, reprehenderit quisquam laboriosam natus, fugit deserunt ab incidunt. Corporis, nulla quo. Excepturi, perferendis porro?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, et! Dignissimos est alias labore eos tenetur incidunt magnam odio doloribus? Incidunt labore molestias ut natus ab odit soluta repellendus iusto.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quasi doloribus dignissimos! Aspernatur officia labore dolorem culpa, architecto facere alias illo eaque non modi adipisci quo, voluptas, esse saepe laudantium.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem officiis numquam quia eveniet assumenda, eligendi harum repudiandae quidem soluta eaque nihil culpa perferendis necessitatibus id quisquam provident iste cupiditate consequatur?",
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus laudantium aspernatur quaerat praesentium laboriosam nemo excepturi ad delectus? Adipisci fuga ipsum est. Officiis blanditiis ab velit unde, recusandae maiores quia?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci excepturi, sunt dolore, reprehenderit illo atque corporis dignissimos repudiandae quos commodi similique molestias quis, debitis nemo eius. Quasi aspernatur recusandae magni.",
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur harum quaerat expedita deserunt. Numquam at rerum, consequuntur cumque provident alias atque culpa! Numquam, enim. Expedita minima mollitia consequuntur totam perspiciatis?",
      ],
      comments: [
        "comments Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam officia nihil provident porro maxime, quo quos, reprehenderit quisquam laboriosam natus, fugit deserunt ab incidunt. Corporis, nulla quo. Excepturi, perferendis porro?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, et! Dignissimos est alias labore eos tenetur incidunt magnam odio doloribus? Incidunt labore molestias ut natus ab odit soluta repellendus iusto.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quasi doloribus dignissimos! Aspernatur officia labore dolorem culpa, architecto facere alias illo eaque non modi adipisci quo, voluptas, esse saepe laudantium.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem officiis numquam quia eveniet assumenda, eligendi harum repudiandae quidem soluta eaque nihil culpa perferendis necessitatibus id quisquam provident iste cupiditate consequatur?",
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus laudantium aspernatur quaerat praesentium laboriosam nemo excepturi ad delectus? Adipisci fuga ipsum est. Officiis blanditiis ab velit unde, recusandae maiores quia?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci excepturi, sunt dolore, reprehenderit illo atque corporis dignissimos repudiandae quos commodi similique molestias quis, debitis nemo eius. Quasi aspernatur recusandae magni.",
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur harum quaerat expedita deserunt. Numquam at rerum, consequuntur cumque provident alias atque culpa! Numquam, enim. Expedita minima mollitia consequuntur totam perspiciatis?",
      ],
    },
  },
  7: {
    img: eight,
    location: "Chennai",
    date: "12/08/2021",
    title: "Helping Stray Dogs for better food and Shelter",
    profile: Profile,
    user: "by Chennai Stray Care",
    raised: 25000,
    goal: 50000,
    left: 6,
    value: 50,
    banner: RectImage,
    mbanner: Banner,
    supporters: 925,
    shares: 2162,
    raisedByShare: 19400,
    topSupporters: [
      {
        profile: Profile,
        name: "John Doe",
        amount: 4000,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 2700,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 2400,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 1800,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 1500,
      },
    ],
    content: {
      overview: [
        "overview Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam officia nihil provident porro maxime, quo quos, reprehenderit quisquam laboriosam natus, fugit deserunt ab incidunt. Corporis, nulla quo. Excepturi, perferendis porro?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, et! Dignissimos est alias labore eos tenetur incidunt magnam odio doloribus? Incidunt labore molestias ut natus ab odit soluta repellendus iusto.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quasi doloribus dignissimos! Aspernatur officia labore dolorem culpa, architecto facere alias illo eaque non modi adipisci quo, voluptas, esse saepe laudantium.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem officiis numquam quia eveniet assumenda, eligendi harum repudiandae quidem soluta eaque nihil culpa perferendis necessitatibus id quisquam provident iste cupiditate consequatur?",
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus laudantium aspernatur quaerat praesentium laboriosam nemo excepturi ad delectus? Adipisci fuga ipsum est. Officiis blanditiis ab velit unde, recusandae maiores quia?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci excepturi, sunt dolore, reprehenderit illo atque corporis dignissimos repudiandae quos commodi similique molestias quis, debitis nemo eius. Quasi aspernatur recusandae magni.",
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur harum quaerat expedita deserunt. Numquam at rerum, consequuntur cumque provident alias atque culpa! Numquam, enim. Expedita minima mollitia consequuntur totam perspiciatis?",
      ],
      updates: [
        "updates Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam officia nihil provident porro maxime, quo quos, reprehenderit quisquam laboriosam natus, fugit deserunt ab incidunt. Corporis, nulla quo. Excepturi, perferendis porro?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, et! Dignissimos est alias labore eos tenetur incidunt magnam odio doloribus? Incidunt labore molestias ut natus ab odit soluta repellendus iusto.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quasi doloribus dignissimos! Aspernatur officia labore dolorem culpa, architecto facere alias illo eaque non modi adipisci quo, voluptas, esse saepe laudantium.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem officiis numquam quia eveniet assumenda, eligendi harum repudiandae quidem soluta eaque nihil culpa perferendis necessitatibus id quisquam provident iste cupiditate consequatur?",
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus laudantium aspernatur quaerat praesentium laboriosam nemo excepturi ad delectus? Adipisci fuga ipsum est. Officiis blanditiis ab velit unde, recusandae maiores quia?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci excepturi, sunt dolore, reprehenderit illo atque corporis dignissimos repudiandae quos commodi similique molestias quis, debitis nemo eius. Quasi aspernatur recusandae magni.",
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur harum quaerat expedita deserunt. Numquam at rerum, consequuntur cumque provident alias atque culpa! Numquam, enim. Expedita minima mollitia consequuntur totam perspiciatis?",
      ],
      comments: [
        "comments Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam officia nihil provident porro maxime, quo quos, reprehenderit quisquam laboriosam natus, fugit deserunt ab incidunt. Corporis, nulla quo. Excepturi, perferendis porro?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, et! Dignissimos est alias labore eos tenetur incidunt magnam odio doloribus? Incidunt labore molestias ut natus ab odit soluta repellendus iusto.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quasi doloribus dignissimos! Aspernatur officia labore dolorem culpa, architecto facere alias illo eaque non modi adipisci quo, voluptas, esse saepe laudantium.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem officiis numquam quia eveniet assumenda, eligendi harum repudiandae quidem soluta eaque nihil culpa perferendis necessitatibus id quisquam provident iste cupiditate consequatur?",
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus laudantium aspernatur quaerat praesentium laboriosam nemo excepturi ad delectus? Adipisci fuga ipsum est. Officiis blanditiis ab velit unde, recusandae maiores quia?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci excepturi, sunt dolore, reprehenderit illo atque corporis dignissimos repudiandae quos commodi similique molestias quis, debitis nemo eius. Quasi aspernatur recusandae magni.",
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur harum quaerat expedita deserunt. Numquam at rerum, consequuntur cumque provident alias atque culpa! Numquam, enim. Expedita minima mollitia consequuntur totam perspiciatis?",
      ],
    },
  },
  8: {
    img: nine,
    location: "Chennai",
    date: "12/08/2021",
    title: "Help Stray Dogs and Cats during pandemic situation",
    profile: Profile,
    user: "by Chennai Stray Care",
    raised: 25000,
    goal: 50000,
    left: 6,
    value: 50,
    banner: RectImage,
    mbanner: Banner,
    supporters: 925,
    shares: 2162,
    raisedByShare: 19400,
    topSupporters: [
      {
        profile: Profile,
        name: "John Doe",
        amount: 4000,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 2700,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 2400,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 1800,
      },
      {
        profile: Profile,
        name: "John Doe",
        amount: 1500,
      },
    ],
    content: {
      overview: [
        "overview Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam officia nihil provident porro maxime, quo quos, reprehenderit quisquam laboriosam natus, fugit deserunt ab incidunt. Corporis, nulla quo. Excepturi, perferendis porro?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, et! Dignissimos est alias labore eos tenetur incidunt magnam odio doloribus? Incidunt labore molestias ut natus ab odit soluta repellendus iusto.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quasi doloribus dignissimos! Aspernatur officia labore dolorem culpa, architecto facere alias illo eaque non modi adipisci quo, voluptas, esse saepe laudantium.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem officiis numquam quia eveniet assumenda, eligendi harum repudiandae quidem soluta eaque nihil culpa perferendis necessitatibus id quisquam provident iste cupiditate consequatur?",
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus laudantium aspernatur quaerat praesentium laboriosam nemo excepturi ad delectus? Adipisci fuga ipsum est. Officiis blanditiis ab velit unde, recusandae maiores quia?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci excepturi, sunt dolore, reprehenderit illo atque corporis dignissimos repudiandae quos commodi similique molestias quis, debitis nemo eius. Quasi aspernatur recusandae magni.",
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur harum quaerat expedita deserunt. Numquam at rerum, consequuntur cumque provident alias atque culpa! Numquam, enim. Expedita minima mollitia consequuntur totam perspiciatis?",
      ],
      updates: [
        "updates Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam officia nihil provident porro maxime, quo quos, reprehenderit quisquam laboriosam natus, fugit deserunt ab incidunt. Corporis, nulla quo. Excepturi, perferendis porro?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, et! Dignissimos est alias labore eos tenetur incidunt magnam odio doloribus? Incidunt labore molestias ut natus ab odit soluta repellendus iusto.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quasi doloribus dignissimos! Aspernatur officia labore dolorem culpa, architecto facere alias illo eaque non modi adipisci quo, voluptas, esse saepe laudantium.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem officiis numquam quia eveniet assumenda, eligendi harum repudiandae quidem soluta eaque nihil culpa perferendis necessitatibus id quisquam provident iste cupiditate consequatur?",
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus laudantium aspernatur quaerat praesentium laboriosam nemo excepturi ad delectus? Adipisci fuga ipsum est. Officiis blanditiis ab velit unde, recusandae maiores quia?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci excepturi, sunt dolore, reprehenderit illo atque corporis dignissimos repudiandae quos commodi similique molestias quis, debitis nemo eius. Quasi aspernatur recusandae magni.",
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur harum quaerat expedita deserunt. Numquam at rerum, consequuntur cumque provident alias atque culpa! Numquam, enim. Expedita minima mollitia consequuntur totam perspiciatis?",
      ],
      comments: [
        "comments Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam officia nihil provident porro maxime, quo quos, reprehenderit quisquam laboriosam natus, fugit deserunt ab incidunt. Corporis, nulla quo. Excepturi, perferendis porro?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, et! Dignissimos est alias labore eos tenetur incidunt magnam odio doloribus? Incidunt labore molestias ut natus ab odit soluta repellendus iusto.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quasi doloribus dignissimos! Aspernatur officia labore dolorem culpa, architecto facere alias illo eaque non modi adipisci quo, voluptas, esse saepe laudantium.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem officiis numquam quia eveniet assumenda, eligendi harum repudiandae quidem soluta eaque nihil culpa perferendis necessitatibus id quisquam provident iste cupiditate consequatur?",
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus laudantium aspernatur quaerat praesentium laboriosam nemo excepturi ad delectus? Adipisci fuga ipsum est. Officiis blanditiis ab velit unde, recusandae maiores quia?",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci excepturi, sunt dolore, reprehenderit illo atque corporis dignissimos repudiandae quos commodi similique molestias quis, debitis nemo eius. Quasi aspernatur recusandae magni.",
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur harum quaerat expedita deserunt. Numquam at rerum, consequuntur cumque provident alias atque culpa! Numquam, enim. Expedita minima mollitia consequuntur totam perspiciatis?",
      ],
    },
  },
};

export default assets;
